#if !canImport(ObjectiveC)
import XCTest

extension WebSocketTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WebSocketTests = [
        ("testWebSocketEcho", testWebSocketEcho),
        ("testWebSocketTLSEcho", testWebSocketTLSEcho),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(WebSocketTests.__allTests__WebSocketTests),
    ]
}
#endif
